name: NeoUno
main: me.neoblade298.neouno.Uno
author: [Neoblade298]
version: 1.56
api-version: 1.15
commands:
   uno:
      description: The base command
      usage: /uno
      permission: neouno.player